# Generated by Django 5.2.7 on 2025-11-01 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OK', 'Confirmada'), ('CXX', 'Cancelada'), ('PENDING', 'Pendiente')], default='PENDING', max_length=20)),
                ('agency', models.CharField(max_length=100)),
                ('booking_code', models.CharField(max_length=50, unique=True)),
                ('clients_names', models.TextField()),
                ('hotel', models.CharField(max_length=200)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('hotel_confirmation', models.CharField(blank=True, max_length=100)),
                ('pax', models.IntegerField()),
                ('room_type', models.CharField(max_length=50)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('touch_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('valid_rates', models.TextField(blank=True)),
                ('nationality', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
