# Generated by Django 4.2.25 on 2025-11-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date_from']},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='pax',
        ),
        migrations.AddField(
            model_name='reservation',
            name='meal_plan',
            field=models.TextField(blank=True, verbose_name='Plan de Comidas'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pax_ad',
            field=models.IntegerField(default=0, verbose_name='PAX Adultos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='pax_chd',
            field=models.IntegerField(default=0, verbose_name='PAX Niños'),
            preserve_default=False,
        ),
    ]
