# Generated by Django 4.2.25 on 2025-11-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_options_remove_reservation_pax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='pax_ad',
            field=models.IntegerField(default=0, verbose_name='PAX Adultos'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pax_chd',
            field=models.IntegerField(default=0, verbose_name='PAX Niños'),
        ),
    ]
