# Generated by Django 4.2.25 on 2025-11-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_pax_ad_alter_reservation_pax_chd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='pax_ad',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='PAX Adultos'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pax_chd',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='PAX Niños'),
        ),
    ]
